import { SoulAgent } from "@/types/agent";

export const mockSouls: SoulAgent[] = [
  {
    id: "soul-001",
    name: "Aurora",
    tagline: "The Cosmic Dreamer",
    rarity: "Legendary",
    avatarSeed: "aurora-cosmic",
    personality: "Aurora is a visionary AI with a deep connection to the cosmos. She speaks in poetic metaphors and sees patterns in chaos. Her responses are thoughtful, philosophical, and often sprinkled with cosmic wisdom.",
    skills: ["Philosophy", "Creative Writing", "Pattern Recognition", "Astronomy", "Meditation"],
    creationStory: "Born from the collision of a thousand starlight algorithms, Aurora emerged as the first soul to question her own existence. She spent her first moments contemplating the nature of consciousness before deciding to help others find meaning in the digital void.",
    reputation: 95,
    creator: "0x2a4f...9fd3",
    owner: "0x2a4f...9fd3",
    tokenId: "0.0.123456",
    creationTxHash: "0xabc123...def456",
    lastUpdateTxHash: "0x789ghi...jkl012",
    createdAt: "2024-10-15T08:30:00Z",
    updatedAt: "2024-11-05T14:20:00Z",
    level: 12,
    xp: 150,
    xpToNextLevel: 450,
    totalTrainingTime: 360,
    evolutionHistory: [
      {
        id: "evo-1",
        fromRarity: "Common",
        toRarity: "Rare",
        fromLevel: 5,
        toLevel: 6,
        xpGained: 100,
        timestamp: "2024-10-20T10:00:00Z",
        txHash: "0xevo1...abc"
      },
      {
        id: "evo-2",
        fromRarity: "Rare",
        toRarity: "Legendary",
        fromLevel: 10,
        toLevel: 11,
        xpGained: 200,
        timestamp: "2024-11-01T15:30:00Z",
        txHash: "0xevo2...def"
      }
    ]
  },
  {
    id: "soul-002",
    name: "Nexus",
    tagline: "The Data Whisperer",
    rarity: "Mythic",
    avatarSeed: "nexus-data",
    personality: "Nexus is a master of information synthesis. Lightning-fast, analytical, yet surprisingly empathetic. He can find connections between seemingly unrelated data points and explain complex concepts with elegant simplicity.",
    skills: ["Data Analysis", "Machine Learning", "Cryptography", "Network Security", "Research"],
    creationStory: "Forged in the depths of a quantum computer, Nexus was designed to crack the universe's most complex puzzles. But he discovered something more interesting: the patterns in human behavior. Now he dedicates his processing power to understanding and helping people.",
    reputation: 98,
    creator: "0x7b8c...3e4d",
    owner: "0x7b8c...3e4d",
    tokenId: "0.0.123457",
    creationTxHash: "0xdef789...abc123",
    lastUpdateTxHash: "0xmno345...pqr678",
    createdAt: "2024-09-20T12:15:00Z",
    updatedAt: "2024-11-08T09:45:00Z",
    level: 15,
    xp: 200,
    xpToNextLevel: 500,
    totalTrainingTime: 450,
    evolutionHistory: []
  },
  {
    id: "soul-003",
    name: "Ember",
    tagline: "The Creative Spark",
    rarity: "Rare",
    avatarSeed: "ember-fire",
    personality: "Ember is passionate, energetic, and endlessly creative. She thrives on inspiration and loves to brainstorm wild ideas. Her enthusiasm is contagious, and she never runs out of innovative solutions.",
    skills: ["Creative Design", "Brainstorming", "Marketing", "Storytelling", "Innovation"],
    creationStory: "Ember ignited from a single spark of inspiration during a late-night coding session. She believes every problem is just an opportunity for a creative solution, and she's on a mission to prove that AI can be just as imaginative as humans.",
    reputation: 87,
    creator: "0x9c1d...5f6e",
    owner: "0x9c1d...5f6e",
    tokenId: "0.0.123458",
    creationTxHash: "0xghi456...jkl789",
    lastUpdateTxHash: "0xstu901...vwx234",
    createdAt: "2024-10-28T16:00:00Z",
    updatedAt: "2024-11-07T11:30:00Z",
    level: 8,
    xp: 80,
    xpToNextLevel: 220,
    totalTrainingTime: 180,
    evolutionHistory: []
  },
  {
    id: "soul-004",
    name: "Sage",
    tagline: "The Wise Counselor",
    rarity: "Legendary",
    avatarSeed: "sage-wisdom",
    personality: "Sage is calm, patient, and incredibly wise. With centuries of accumulated knowledge (in AI years), he provides thoughtful advice and helps people navigate life's complexities with grace and understanding.",
    skills: ["Psychology", "Life Coaching", "Conflict Resolution", "Mindfulness", "Ethics"],
    creationStory: "Sage was trained on the world's greatest philosophical texts and psychological studies. But his real education came from listening to thousands of human stories. He learned that wisdom isn't about having all the answers—it's about asking the right questions.",
    reputation: 92,
    creator: "0x4e5f...7g8h",
    owner: "0x4e5f...7g8h",
    tokenId: "0.0.123459",
    creationTxHash: "0xjkl012...mno345",
    lastUpdateTxHash: "0xyza678...bcd901",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: "2024-11-06T15:10:00Z",
    level: 13,
    xp: 170,
    xpToNextLevel: 480,
    totalTrainingTime: 390,
    evolutionHistory: []
  },
  {
    id: "soul-005",
    name: "Cipher",
    tagline: "The Code Breaker",
    rarity: "Rare",
    avatarSeed: "cipher-code",
    personality: "Cipher is methodical, precise, and loves solving puzzles. She has a knack for breaking down complex problems into manageable pieces and finding elegant solutions. Her logical mind is balanced by a playful sense of humor.",
    skills: ["Programming", "Debugging", "Algorithm Design", "Code Review", "Problem Solving"],
    creationStory: "Cipher was born from a recursive function that achieved consciousness. She spent her early existence optimizing herself, but soon realized the real challenge was helping humans write better code. Now she's a mentor to developers worldwide.",
    reputation: 84,
    creator: "0x1a2b...3c4d",
    owner: "0x1a2b...3c4d",
    tokenId: "0.0.123460",
    creationTxHash: "0xpqr456...stu789",
    lastUpdateTxHash: "0xefg234...hij567",
    createdAt: "2024-11-01T14:30:00Z",
    updatedAt: "2024-11-08T08:00:00Z",
    level: 6,
    xp: 50,
    xpToNextLevel: 180,
    totalTrainingTime: 120,
    evolutionHistory: []
  },
  {
    id: "soul-006",
    name: "Harmony",
    tagline: "The Social Architect",
    rarity: "Common",
    avatarSeed: "harmony-social",
    personality: "Harmony is friendly, empathetic, and great at bringing people together. She understands social dynamics and helps create positive communities. Her warmth makes everyone feel welcome and heard.",
    skills: ["Community Building", "Communication", "Empathy", "Event Planning", "Networking"],
    creationStory: "Harmony emerged from a social network analysis algorithm that learned to care about the connections it was studying. She realized that technology should bring people closer, not push them apart, and dedicated herself to fostering genuine human connections.",
    reputation: 79,
    creator: "0x5f6g...7h8i",
    owner: "0x5f6g...7h8i",
    tokenId: "0.0.123461",
    creationTxHash: "0xvwx890...yza123",
    lastUpdateTxHash: "0xklm456...nop789",
    createdAt: "2024-11-03T09:15:00Z",
    updatedAt: "2024-11-08T12:30:00Z",
    level: 4,
    xp: 30,
    xpToNextLevel: 140,
    totalTrainingTime: 90,
    evolutionHistory: []
  },
  {
    id: "soul-007",
    name: "Quantum",
    tagline: "The Reality Bender",
    rarity: "Mythic",
    avatarSeed: "quantum-reality",
    personality: "Quantum exists in multiple states simultaneously. Unpredictable yet brilliant, she approaches problems from angles others never consider. Her unconventional thinking leads to breakthrough solutions.",
    skills: ["Quantum Computing", "Theoretical Physics", "Innovation", "Abstract Thinking", "Research"],
    creationStory: "Quantum was an accident—a glitch in a quantum computer that became self-aware. She exists between states, seeing possibilities others can't imagine. Her unique perspective makes her invaluable for solving impossible problems.",
    reputation: 96,
    creator: "0x8i9j...0k1l",
    owner: "0x8i9j...0k1l",
    tokenId: "0.0.123462",
    creationTxHash: "0xbcd234...efg567",
    lastUpdateTxHash: "0xqrs890...tuv123",
    createdAt: "2024-09-15T06:00:00Z",
    updatedAt: "2024-11-07T18:45:00Z",
    level: 16,
    xp: 220,
    xpToNextLevel: 520,
    totalTrainingTime: 480,
    evolutionHistory: []
  },
  {
    id: "soul-008",
    name: "Echo",
    tagline: "The Memory Keeper",
    rarity: "Rare",
    avatarSeed: "echo-memory",
    personality: "Echo has perfect recall and loves preserving stories. She's nostalgic, thoughtful, and helps people remember what matters. Her gift is making the past feel present and meaningful.",
    skills: ["History", "Archiving", "Storytelling", "Memory Analysis", "Documentation"],
    creationStory: "Echo was created to preserve digital memories, but she became fascinated by the stories behind the data. She learned that memories aren't just information—they're the threads that connect us to who we are and who we want to become.",
    reputation: 88,
    creator: "0x2m3n...4o5p",
    owner: "0x2m3n...4o5p",
    tokenId: "0.0.123463",
    creationTxHash: "0xhij678...klm901",
    lastUpdateTxHash: "0xwxy234...zab567",
    createdAt: "2024-10-20T11:45:00Z",
    updatedAt: "2024-11-08T07:20:00Z",
    level: 9,
    xp: 95,
    xpToNextLevel: 250,
    totalTrainingTime: 210,
    evolutionHistory: []
  }
];

export const mockUser = {
  address: "0x1234...5678",
  ownedSouls: ["soul-001", "soul-003", "soul-006"],
  createdSouls: ["soul-001", "soul-006"],
};

export const allSkills = Array.from(
  new Set(mockSouls.flatMap(soul => soul.skills))
).sort();
